config/routes.rb
Rails.application.routes.draw do

  get 'bookmarks/index'
  get 'bookmarks/create'

  get 'bookmarks/destroy'

  get 'comments/create'

  get 'comments/destroy'

  root 'page#landing'

  get 'photos/destroy'
  get 'page/home', as: 'home'

  devise_for :users

  resources :recipes
  resources :users, only: [:show]
  resources :photos
  resources :recipes do
    resources :comments, only: [:create, :destroy]
    resources :bookmarks, only: [ :create, :destroy ]
    resources :likes, only: [ :create, :destroy ]
  end

  resources :users, only: [:show] do
    member do
      get :following, :followers
    end
  end

  #resources :relationships, only: [:create, :destroy]

  post '/relation/:following_id', to: 'relationships#build', as: :build_fellowship
  delete '/relation/:following_id', to: 'relationships#over', as: :over_fellowship
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :file, PhotoUploader
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_one :main_photo, class_name: 'Photo'
  belongs_to :user

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, length: {maximum: 50}
  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", 
    foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :likes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  


  def add_bookmark?(recipe_id)
    if has_bookmark?(recipe_id)
      return false
    else
      Bookmark.create!(user_id: self.id, recipe_id: recipe_id)
    end

  end

  def delete_bookmark?(recipe_id)
    unless has_bookmark?(recipe_id)
      return false
    else
      Bookmark.where(user_id: self.id, recipe_id: recipe_id).delete_all
      return true
    end
  end

  def has_bookmark?(recipe_id)
    Bookmark.exists?(user_id: self.id, recipe_id: recipe_id)
  end

  def add_like?(recipe_id)
    if has_like?(recipe_id)
      return false
    else
      Like.create!(user_id: self.id, recipe_id: recipe_id)
    end

  end

  def delete_like?(recipe_id)
    unless has_like?(recipe_id)
      return false
    else
      Like.where(user_id: self.id, recipe_id: recipe_id).delete_all
      return true
    end
  end

  def has_like?(recipe_id)
    Like.exists?(user_id: self.id, recipe_id: recipe_id)
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!


  def create
    load_recipe

    respond_to do |format|
      if current_user.add_bookmark?(params[:recipe_id])
        format.js
      else
        format.json { render json: {status: :failed} }
      end
    end

  end

  def index
    @bookmarks = current_user.bookmarks
    @user = current_user
  end

  def destroy
    load_recipe

    respond_to do |format|
      if current_user.delete_bookmark?(params[:recipe_id])
        format.js
      else
        format.json { render json: {status: :failed} }
      end
    end
  end

  private

  def load_recipe
    @recipe = Recipe.find_by_id(params[:recipe_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    load_recipe

    respond_to do |format|
      if current_user.add_like?(params[:recipe_id])
        format.js
      else
        format.json { render json: {status: :failed} }
      end
    end

  end

  def destroy
    load_recipe

    respond_to do |format|
      if current_user.delete_like?(params[:recipe_id])
        format.js
      else
        format.json { render json: {status: :failed} }
      end
    end
  end

  private

  def load_recipe
    @recipe = Recipe.find_by_id(params[:recipe_id])
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
    if(user_signed_in?)
      @recipes= []
      @followings = current_user.following

      if @followings
        @followings.each do |following|
          following.recipes.each do |recipe|
            unless @recipes.include? recipe
              @recipes << recipe
            end
          end
        end
      end

      current_user.recipes.each do |recipe|
        @recipes << recipe
      end

      @recipes = @recipes.sort_by {|e| e[:create_at]}.reverse
    else
      redirect_to root_path
    end
  end

  def landing
    if user_signed_in?
      redirect_to home_path
    end

  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    @photo = Photo.find(params[:id])
    recipe = @photo.recipe

    @photo.destroy
    @photos = Photo.where(recipe_id: recipe.id)

    respond_to :js
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identical&s=150"
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/_bookmark_button.html.erb
<% if current_user.has_bookmark?(recipe.id)%>
  <%= link_to recipe_bookmark_path(recipe_id: recipe.id, id: 0),
    remote: true,
    method: 'delete',
    id: "button-bookmark-recipe-#{recipe.id}" do %>
      <span class= "btn" title="Unbookmark"><i class="fa fa-bookmark bookmark" aria-hidden="true"></i></span>
  <% end %>
<% else %>
  <%= link_to recipe_bookmarks_path(recipe_id: recipe.id),
    remote: true,
    method: 'post',
    id: "button-bookmark-recipe-#{recipe.id}" do %>
      <span class= "btn" title="Bookmark"><i class="fa fa-bookmark-o bookmark" aria-hidden="true"></i></span>
  <% end %>
<% end %>

app/views/bookmarks/create.js.erb
$("#button-bookmark-recipe-<%= @recipe.id %>").replaceWith("<%= j render partial: 'bookmarks/bookmark_button', locals: { recipe: @recipe } %>")

app/views/bookmarks/destroy.js.erb
$("#button-bookmark-recipe-<%= @recipe.id %>").replaceWith("<%= j render partial: 'bookmarks/bookmark_button', locals: { recipe: @recipe } %>")

app/views/bookmarks/index.html.erb
<script>
  new WOW().init();
</script>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="row jumbotron cover-wrap">
      <div class="col-3 text-center">
        <%= image_tag avatar_url(@user), class: "img-circle w-50" %>
        <p class= "user-name-cover"> <%= @user.name %> </p>
        <a id="followers-count-user" href="#"><%= @user.followers.count %> follower</a>
      </div>
      <div class="col-9">
        <br>
        <p style="font-size:3em">All your bookmarks</p>
        <br>
      </div>
    </div>


    <div class="row mt-10" style="margin-top: 30px">
      <ul class="card-columns">
        <% if @user.bookmarks.any? %>
          <% @user.bookmarks.each do |bookmark| %>
            <%= render partial: 'shared/recipe_small', locals: {recipe: bookmark.recipe} %>
          <% end %>
        <% else %>
      </ul>
    </div>
          <div class="jumbotron">
            <% if current_user.name == @user.name %>
              <h2>You don't have any bookmark!</h2>
            <% end %>
          </div>
        <% end %>
  </div>
</div>