config/routes.rb
Rails.application.routes.draw do

  get 'bookmarks/index'
  get 'bookmarks/create'

  get 'bookmarks/destroy'

  get 'comments/create'

  get 'comments/destroy'

  root 'page#landing'

  get 'photos/destroy'
  get 'page/home', as: 'home'

  devise_for :users

  resources :recipes
  resources :users, only: [:show]
  resources :photos
  resources :recipes do
    resources :comments, only: [:create, :destroy]
    resources :bookmarks, only: [ :create, :destroy ]
    resources :likes, only: [ :create, :destroy ]
  end

  resources :users, only: [:show] do
    member do
      get :following, :followers
    end
  end

  #resources :relationships, only: [:create, :destroy]

  post '/relation/:following_id', to: 'relationships#build', as: :build_fellowship
  delete '/relation/:following_id', to: 'relationships#over', as: :over_fellowship
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :file, PhotoUploader
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_one :main_photo, class_name: 'Photo'
  belongs_to :user

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, length: {maximum: 50}
  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", 
    foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :likes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  


  def add_bookmark?(recipe_id)
    if has_bookmark?(recipe_id)
      return false
    else
      Bookmark.create!(user_id: self.id, recipe_id: recipe_id)
    end

  end

  def delete_bookmark?(recipe_id)
    unless has_bookmark?(recipe_id)
      return false
    else
      Bookmark.where(user_id: self.id, recipe_id: recipe_id).delete_all
      return true
    end
  end

  def has_bookmark?(recipe_id)
    Bookmark.exists?(user_id: self.id, recipe_id: recipe_id)
  end

  def add_like?(recipe_id)
    if has_like?(recipe_id)
      return false
    else
      Like.create!(user_id: self.id, recipe_id: recipe_id)
    end

  end

  def delete_like?(recipe_id)
    unless has_like?(recipe_id)
      return false
    else
      Like.where(user_id: self.id, recipe_id: recipe_id).delete_all
      return true
    end
  end

  def has_like?(recipe_id)
    Like.exists?(user_id: self.id, recipe_id: recipe_id)
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    load_recipe

    respond_to do |format|
      if current_user.add_like?(params[:recipe_id])
        format.js
      else
        format.json { render json: {status: :failed} }
      end
    end

  end

  def destroy
    load_recipe

    respond_to do |format|
      if current_user.delete_like?(params[:recipe_id])
        format.js
      else
        format.json { render json: {status: :failed} }
      end
    end
  end

  private

  def load_recipe
    @recipe = Recipe.find_by_id(params[:recipe_id])
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
    if(user_signed_in?)
      @recipes= []
      @followings = current_user.following

      if @followings
        @followings.each do |following|
          following.recipes.each do |recipe|
            unless @recipes.include? recipe
              @recipes << recipe
            end
          end
        end
      end

      current_user.recipes.each do |recipe|
        @recipes << recipe
      end

      @recipes = @recipes.sort_by {|e| e[:create_at]}.reverse
    else
      redirect_to root_path
    end
  end

  def landing
    if user_signed_in?
      redirect_to home_path
    end

  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    @photo = Photo.find(params[:id])
    recipe = @photo.recipe

    @photo.destroy
    @photos = Photo.where(recipe_id: recipe.id)

    respond_to :js
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]


  def index
     @recipes = if params[:term]
     Recipe.where('title LIKE ?', "%#{params[:term]}%")
   else
    current_user.recipes
  end

  end

  def show
    @photos = @recipe.photos
    @image = @photos.first
    @comments = @recipe.comments
    @hasComment = @comments.find_by(user_id: current_user.id) if current_user
  end

  def new
    @recipe = current_user.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      if params[:images]
        params[:images].each do |image|
          @recipe.photos.create(file: image)
        end
      end

      @photos = @recipe.photos
      # redirect_to edit_recipe_path(@recipe), notice: "Publish success!"
      redirect_to home_path, notice: "Publish success!"
    else
      render :new
    end
  end

  def edit
    if current_user.id = @recipe.user_id
      @photos = @recipe.photos
    else
      redirect_to root_path, notice: "You don't have permission."
    end
  end

  def update
    if @recipe.update(recipe_params)
      if params[:images]
        params[:images].each do |image|
          @recipe.photos.create(file: image)
        end
      end

      redirect_to edit_recipe_path(@recipe), notice: "Update success!"
    else
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @photos = @recipe.photos
    @photos.each do |photo|
      photo.destroy
    end
    @recipe.destroy
    redirect_to home_path
  end

  def self.search(term)
    if term
      Recipe.where('title LIKE ?', "%#{params[:term]}%").order('id DESC')
    else
      @recipes = current_user.recipes.order('id DESC') 
    end

    redirect_to home_path
  end

  private
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:title, :describe, :ingredients, :serving, :method, :term)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identical&s=150"
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/_like_button.html.erb
<% if current_user.has_like?(recipe.id)%>
  <%= link_to recipe_like_path(recipe_id: recipe.id, id: 0),
    remote: true,
    method: 'delete',
    id: "button-like-recipe-#{recipe.id}" do %>
      <span class= "btn" title="Unlike"><i class="fa fa-heart like" aria-hidden="true"></i></span>
  <% end %>
<% else %>
  <%= link_to recipe_likes_path(recipe_id: recipe.id),
    remote: true,
    method: 'post',
    id: "button-like-recipe-#{recipe.id}" do %>
      <span class= "btn" title="Like"><i class="fa fa-heart-o like" aria-hidden="true"></i></span>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$("#button-like-recipe-<%= @recipe.id %>").replaceWith("<%= j render partial: 'likes/like_button', locals: { recipe: @recipe } %>");

$("#count-like-<%= @recipe.id %>").replaceWith("<span id=\"count-like-<%= @recipe.id %>\"> <%= @recipe.likes.count %></span>")

app/views/likes/destroy.html.erb
$("#button-like-recipe-<%= @recipe.id %>").replaceWith("<%= j render partial: 'likes/like_button', locals: { recipe: @recipe } %>")

app/views/likes/destroy.js.erb
$("#button-like-recipe-<%= @recipe.id %>").replaceWith("<%= j render partial: 'likes/like_button', locals: { recipe: @recipe } %>");

$("#count-like-<%= @recipe.id %>").replaceWith("<span id=\"count-like-<%= @recipe.id %>\"> <%= @recipe.likes.count %></span>")

app/views/photos/_list.html.erb
<% if @photos %>
  <div class="row">
    <% @photos.each do |photo| %>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading preview">
            <%= image_tag photo.file %>
          </div>
          <div class="panel-body">
            <span class="pull-right">
              <%= link_to photo, remote: true, method: :delete, data: {confirm: "Are you sure?"} do %>
                <i class="fa fa-times fa-lg"></i>
              <% end %>
            </span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/photos/destroy.js.erb
$('#photos').html("<%= j render 'photos/list' %>")

app/views/recipes/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Create your recipe!
  </div>

  <div class="panel-body">
    <div class="container">

      <%= form_for @recipe, html: {multipart: true} do |f| %>

        <div class="row">
          <div class=col-md-10>
            <div class="form-group">
              <%= f.text_field :title, placeholder: "Recipe title", class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.text_area :describe, rows: 5, placeholder: "Tell the story of the recipe", class: "form-control" %>
            </div>

            <div class="form-group">
              <label>Ingredients</label>
              <%= f.text_area :ingredients, rows: 5, placeholder: "100g meat", class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.number_field :serving, rows: 5, placeholder: "How many servings?", class: "form-control" %>
            </div>

            <div class="form-group">
              <label>Method</label>
              <%= f.text_area :method, rows:16, placeholder: "Step by step", class: "form-control" %>
            </div>
          </div>
        </div>

        <script language="javascript">CKEDITOR.replace('recipe_method');</script>


        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <span class="btn btn-default btn-file">
                <i class="fa fa-cloud-upload fa -lg"></i> Upload Photos
                <%= file_field_tag "images[]", type: :file, multiple: true %>
              </span>
            </div>
          </div>
        </div>


        <div id="photos">
          <%= render 'photos/list' %>
        </div>


        <div class="actions">
          <%= f.submit "Publish", class: "btn btn-primary" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/edit.html.erb
<%= render 'form' %>

app/views/recipes/index.html.erb
<button class="btn btn-primary search-wrap" type="button">
  Search result <span class="badge"><%=@recipes.count%></span>
</button>
<% if @recipes %>
  <div class="card-columns">
    <% @recipes.each do |recipe| %>
      <%= render partial: 'shared/recipe_small', locals: { recipe: recipe } %>
    <% end %>
  </div>
<% else %>
  <div>
    We don't have any recipe. Follow other or create new recipe.
  </div>
<% end %>

app/views/recipes/new.html.erb
<%= render 'form' %>

app/views/recipes/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-12 col-sm-6 col-md-2"></div>

		<div class="col-xs-12 col-sm-6 col-md-8">
			<div class = "wrap-img">
				<%= image_tag @image.file , class: "img-rounded", alt: "image foodsky", width:"100%" %>
			</div>
			<div class = "wrap-content">
				<h1 class="title-recipes"><%= @recipe.title %> <i class="fa fa-star" aria-hidden="true"></i></h1>
				<div class="page-header">
					<%= image_tag avatar_url(@recipe.user), class: "img-circle avatar-medium" %>
					<strong class= "user-name">
						<%= link_to  @recipe.user.name, user_path(@recipe.user), class: "" %></strong>
					<p style="margin-top: 5px;">
            <% if current_user.id != @recipe.user.id %>
              <%= render partial: 'shared/follow_button', locals: { target: @recipe.user } %>
            <% end %>
            <%= render partial: 'likes/like_button', locals: {recipe: @recipe} %>
            <span id="count-like-<%= @recipe.id %>"> <%= @recipe.likes.count %></span>
            <%= render partial: 'bookmarks/bookmark_button', locals: { recipe: @recipe } %>
					</p>
					<% if current_user.name == @recipe.user.name %>
						<h3 style="color:#3c763d">
							<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
							<%= link_to "Edit recipes", edit_recipe_path(@recipe) %>
						</h3>
						<h3 style="color:#3c763d">
			            	<i class="fa fa-trash" aria-hidden="true"></i>
			            	<%= link_to "Delete recipes", recipe_path(@recipe), method: :delete, data: {confirm: "Are you sure?"} %>
						</h3>
					<% end %>
				</div>
				<button class="btn btn-primary servings" type="button">
					Servings <span class="badge"><%= @recipe.serving %></span>
				</button>

				<div class="panel panel-info">
					<div class="panel-heading"><i class="fa fa-newspaper-o" aria-hidden="true"></i> Story of the recipes</div>
					<div class="panel-body">
				    	<%= simple_format(@recipe.describe) %>
					</div>
				</div>

				<div class="panel panel-info">
					<div class="panel-heading"><i class="fa fa-shopping-basket" aria-hidden="true"></i> Ingredients</div>
					<div class="panel-body">
				    	<%= simple_format(@recipe.ingredients) %>
					</div>
				</div>

				<div class="panel panel-info">
					<div class="panel-heading"><i class="fa fa-th-list" aria-hidden="true"></i> Method</div>
					<div class="panel-body">
              <%= @recipe.method.html_safe %>
					</div>
				</div>

		        <%= render 'comments/create_form' %>
		        <%= render 'comments/list' %>
			</div>		
		</div>
		<div class="col-xs-12 col-sm-6 col-md-2"></div>		
	</div>
</div>

app/views/recipes/update.html.erb
<h1>Recipes#update</h1>
<p>Find me in app/views/recipes/update.html.erb</p>

app/views/users/show.html.erb
<script>
  new WOW().init();
</script>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="row jumbotron cover-wrap">
      <div class="col-3 text-center">
        <%= image_tag avatar_url(@user), class: "img-circle w-50" %>
        <p class= "user-name-cover"> <%= @user.name %> </p>
        <a id="followers-count-user" href="#"><%= @user.followers.count %> follower</a>
      </div>
      <div class="col-9">
        <p>Share recipes!</p>
        <br>
        <p>            Share your knowledge!</p>
        <br>
        <p>                        Share your passion!</p>
        <% if current_user.id != @user.id %>
          <%= render partial: 'shared/follow_button', locals: { target: @user } %>
        <% end %>
      </div>
    </div>


    <div class="row mt-10" style="margin-top: 30px">
      <ul class="card-columns">
        <% if @user.recipes.any? %>
          <% @user.recipes.each do |recipe| %>
            <%= render partial: 'shared/recipe_small', locals: {recipe: recipe} %>
          <% end %>
        <% else %>
      </ul>
    </div>
          <div class="jumbotron">
            <% if current_user.name == @user.name %>
              <h2>You don't have any recipes. Create recipe now!</h2>
              <p></p>
              <%= link_to "Create recipe now", new_recipe_path, class: "btn btn-primary btn-lg" %>
            <% else %>
              <h2>This user haven't had any recipes yet!</h2>
            <% end %>
          </div>
        <% end %>
  </div>
</div>