config/routes.rb
Rails.application.routes.draw do

  get 'bookmarks/index'
  get 'bookmarks/create'

  get 'bookmarks/destroy'

  get 'comments/create'

  get 'comments/destroy'

  root 'page#landing'

  get 'photos/destroy'
  get 'page/home', as: 'home'

  devise_for :users

  resources :recipes
  resources :users, only: [:show]
  resources :photos
  resources :recipes do
    resources :comments, only: [:create, :destroy]
    resources :bookmarks, only: [ :create, :destroy ]
    resources :likes, only: [ :create, :destroy ]
  end

  resources :users, only: [:show] do
    member do
      get :following, :followers
    end
  end

  #resources :relationships, only: [:create, :destroy]

  post '/relation/:following_id', to: 'relationships#build', as: :build_fellowship
  delete '/relation/:following_id', to: 'relationships#over', as: :over_fellowship
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :file, PhotoUploader
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_one :main_photo, class_name: 'Photo'
  belongs_to :user

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, length: {maximum: 50}
  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", 
    foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :likes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  


  def add_bookmark?(recipe_id)
    if has_bookmark?(recipe_id)
      return false
    else
      Bookmark.create!(user_id: self.id, recipe_id: recipe_id)
    end

  end

  def delete_bookmark?(recipe_id)
    unless has_bookmark?(recipe_id)
      return false
    else
      Bookmark.where(user_id: self.id, recipe_id: recipe_id).delete_all
      return true
    end
  end

  def has_bookmark?(recipe_id)
    Bookmark.exists?(user_id: self.id, recipe_id: recipe_id)
  end

  def add_like?(recipe_id)
    if has_like?(recipe_id)
      return false
    else
      Like.create!(user_id: self.id, recipe_id: recipe_id)
    end

  end

  def delete_like?(recipe_id)
    unless has_like?(recipe_id)
      return false
    else
      Like.where(user_id: self.id, recipe_id: recipe_id).delete_all
      return true
    end
  end

  def has_like?(recipe_id)
    Like.exists?(user_id: self.id, recipe_id: recipe_id)
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    load_recipe

    respond_to do |format|
      if current_user.add_like?(params[:recipe_id])
        format.js
      else
        format.json { render json: {status: :failed} }
      end
    end

  end

  def destroy
    load_recipe

    respond_to do |format|
      if current_user.delete_like?(params[:recipe_id])
        format.js
      else
        format.json { render json: {status: :failed} }
      end
    end
  end

  private

  def load_recipe
    @recipe = Recipe.find_by_id(params[:recipe_id])
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
    if(user_signed_in?)
      @recipes= []
      @followings = current_user.following

      if @followings
        @followings.each do |following|
          following.recipes.each do |recipe|
            unless @recipes.include? recipe
              @recipes << recipe
            end
          end
        end
      end

      current_user.recipes.each do |recipe|
        @recipes << recipe
      end

      @recipes = @recipes.sort_by {|e| e[:create_at]}.reverse
    else
      redirect_to root_path
    end
  end

  def landing
    if user_signed_in?
      redirect_to home_path
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identical&s=150"
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodsky</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <style type="text/css" media="screen">
    div {
      font-size:medium !important;
    }
    input{
      font-size:medium !important;
    }
    button{
      font-size:medium !important;
    }
    body{
      font-size:medium !important;
    }

    a{
      font-size:medium !important;
    }
    textarea{
      font-size:medium !important;
    }
    </style>
  </head>
  <% if user_signed_in? %>
    <body>
      <%= render 'shared/navbar' %>
      <%= render 'shared/message' %>
      <div class="container">
        <%= yield %>
      </div>
    </body>
  <% else %>
    <body class="body-bg">
      <%= yield %>
    </body>
  <% end %>
</html>

app/views/page/home.html.erb
<script>
  new WOW().init();
</script>
<% if @recipes %>
  <div class="card-columns">
    <% @recipes.each do |recipe| %>
      <%= render partial: 'shared/recipe_small', locals: { recipe: recipe } %>
    <% end %>
  </div>
<% else %>
  <div>
    We don't have any recipe. Follow other or create new recipe.
  </div>
<% end %>

app/views/page/landing.html.erb
<style type="text/css" media="screen">
	a{
		color:#fff;
		text-decoration: none;
	}
	a:hover{
		color: #fff;
	}
</style>
<script>
  new WOW().init();
</script>
<div class="wrap-landing">
  <div class="content wow fadeInDown">
    <h1>FoodSky</h1>
    <hr style="background-color: #fff; width:120px;">
        <p>Share food recipes... Share your knowledge...</p>
        <p>Share your passion!</p>
    <ul class="button" id="button-login">
        <li>
          <%= link_to "Log In", new_user_session_path, class: "signin" %>
        </li>
        <li>
          <%= link_to "Sign Up", new_user_registration_path, class: "signup" %>
        </li>
    </ul>
    <i class="fa fa-facebook-official fa-2x" aria-hidden="true"></i>
    <i class="fa fa-twitter fa-2x" aria-hidden="true"></i>
    <i class="fa fa-instagram fa-2x" aria-hidden="true"></i>
  </div>
</div>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |msg| %>
      toastr.error('<%= msg %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_follow_button.html.erb
<% if user_signed_in? %>
  <% if current_user.following?(target) %>
    <%=
      link_to over_fellowship_path(following_id: target.id),
        remote: true,
        method: 'delete',
        id: "button-follow-#{target.id}" do %>
          <button class="btn btn-default float-md-right">Unfollow <i class="fa fa-rss" aria-hidden="true"></i></button>
      <% end %>
  <% else %>

    <%=
      link_to build_fellowship_path(following_id: target.id),
        remote: true,
        method: 'post',
        id: "button-follow-#{target.id}" do %>
          <button class="btn btn-primary float-md-right">Follow <i class="fa fa-rss" aria-hidden="true"></i></button>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<div class="container; text">
  <nav class="navbar navbar-toggleable-md navbar-light bg-nav">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "FoodSky", root_path, class: "nav-link navbar-brand foodsky" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" style="color:#fff">About</a>
      </li>
    </ul>
    <%= render partial: 'shared/searchbar' %>
    <ul class="navbar-nav">
      <% unless user_signed_in? %>
        <li><%= link_to "Log In", new_user_session_path, class: "nav-link" %></li>
        <li><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
      <% else %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>
            <span class="user-name-nav"><%= current_user.name %></span>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Create recipe", new_recipe_path, class: "dropdown-item" %>
            <%= link_to "Your Bookmark", bookmarks_index_path, class: "dropdown-item" %>
            <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
    </ul>
  </nav>
</div>

app/views/shared/_recipe_small.html.erb
<div class="card wow fadeInLeft">
  <%= image_tag recipe.photos.first.file, class: "card-img-top img-fluid" %>
  <div class="card-block">
    <h4 class="card-title recipe-title"><%= link_to recipe.title, recipe_path(recipe.id) %></h4>
    <strong class= "user-name">
            <%= link_to  recipe.user.name, user_path(recipe.user), class: "" %></strong>
    <p class="card-text"><%= recipe.describe %></p>
  </div>
  <div class="card-footer">
    <%= render partial: 'likes/like_button', locals: {recipe: recipe} %>
    <span id="count-like-<%= recipe.id %>"> <%= recipe.likes.count %></span>
    <%= render partial: 'bookmarks/bookmark_button', locals: { recipe: recipe } %>
	<small class="text-muted">Last updated <%= distance_of_time_in_words(recipe.created_at, Time.now) %> ago</small>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<%= form_tag(recipes_path, method: :get, class:"navbar-form navbar-left") do %>
  <%= text_field_tag :term, params[:term], class:"form-control", placeholder:"Search" %>
  <%= submit_tag 'Search', title: nil, type:"submit", class:"btn btn-primary" %>
<% end %>